### ISSUE TITLE
Token-based authentication appears to not be working

### ISSUE THREAD

**Issue by PaulFurtado** [harbur/kubernetic-issues#16]
kubectl works fine, my ~/.kube/config is set up as:
```yaml
apiVersion: v1
clusters:
- cluster:
    server: <redacted>
  name: iad03
contexts:
- context:
    cluster: iad03
    user: test-admin
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: test-admin
  user:
    token: <redacted>
```
in the console, I see:
![screenshot from 2017-03-03 15-33-07](https://cloud.githubusercontent.com/assets/704936/23568087/1592b4fc-0027-11e7-87b9-69a8515dc5d7.png)

It's not clear that it's sending the Authorization header along to the server at all. Am I doing anything wrong here?
