### ISSUE TITLE
Can't connect to a google-container hosted instance

### ISSUE THREAD

**Issue by jduhamel** [harbur/kubernetic-issues#7]
Hi, My kubectl works and I get cluster-info as well as all the other stuff but nothing shows up on kubernetic ?

**Comment by spiddy** [comment]
Hi,

currently there is no error-handling yet for loading `~/.kube/config` and if it fails you get a blank screen. So we can review it here to see how to get you started:

- Do you use linux/mac?
- Which version of Kubernetic did you try?
- Do you run `kubectl` as the same user as `Kubernetic`?
- Does the `kubectl cluster-info` works ok without any added flags (choosing context or cluster)
- If the above works then you should have a `~/.kube/config`. (Don't share it - it may contain your credentials)
- Can you show the `kubectl config get-contexts` output (you can obscure your google-project name if you want)
- Inside your `~/.kube/config` what type of fields do you use:

Supported ones are:

```
apiVersion: v1
kind: Config
current_context: ***
clusters:
  - cluster:
    certificate-authority: ***
    certificate-authority-data: ***
    server: ***
  name: ***
contexts:
  - context:
    cluster: ***
    namespace: ***
    user: ***
  name:
users:
  - name: ***
    user:
      client-certificate: ***
      client-key: ***
  - name: ***
    user:
      client-certificate-data: ***
      client-key-data: ***
  - name: ***
    user:
      username: ***
      password: ***
``` 

There is another type of user credential not supported yet:

```
users:
  - name: ***
     user:
       token: ***
```

Can you check your `~/.kube/config` if you use a token for authentication?
